<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class FightController extends Controller
{
    private $effectiveness = [
        'acero' => [
            'acero' => 0.5,
            'agua' => 0.5,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 0.5,
            'fantasma' => 1,
            'fuego' => 0.5,
            'hada' => 2,
            'hielo' => 2,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 1,
            'roca' => 2,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'agua' => [
            'acero' => 1,
            'agua' => 0.5,
            'bicho' => 1,
            'dragon' => 0.5,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 2,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 0.5,
            'psiquico' => 1,
            'roca' => 2,
            'siniestro' => 1,
            'tierra' => 2,
            'veneno' => 1,
            'volador' => 1
        ],
        'bicho' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 0.5,
            'fuego' => 0.5,
            'hada' => 0.5,
            'hielo' => 1,
            'lucha' => 0.5,
            'normal' => 1,
            'planta' => 2,
            'psiquico' => 2,
            'roca' => 1,
            'siniestro' => 2,
            'tierra' => 1,
            'veneno' => 0.5,
            'volador' => 0.5
        ],
        'dragon' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 2,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 1,
            'hada' => 0,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 1,
            'roca' => 1,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'electrico' => [
            'acero' => 1,
            'agua' => 2,
            'bicho' => 1,
            'dragon' => 0.5,
            'electrico' => 0.5,
            'fantasma' => 1,
            'fuego' => 1,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 0.5,
            'psiquico' => 1,
            'roca' => 1,
            'siniestro' => 1,
            'tierra' => 0,
            'veneno' => 1,
            'volador' => 2
        ],
        'fantasma' => [
            'acero' => 1,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 2,
            'fuego' => 1,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 0,
            'planta' => 1,
            'psiquico' => 2,
            'roca' => 1,
            'siniestro' => 0.5,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'fuego' => [
            'acero' => 2,
            'agua' => 0.5,
            'bicho' => 2,
            'dragon' => 0.5,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 0.5,
            'hada' => 1,
            'hielo' => 2,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 2,
            'psiquico' => 1,
            'roca' => 0.5,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'hada' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 2,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 0.5,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 2,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 1,
            'roca' => 1,
            'siniestro' => 2,
            'tierra' => 1,
            'veneno' => 0.5,
            'volador' => 1
        ],
        'hielo' => [
            'acero' => 0.5,
            'agua' => 0.5,
            'bicho' => 1,
            'dragon' => 2,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 0.5,
            'hada' => 1,
            'hielo' => 0.5,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 2,
            'psiquico' => 1,
            'roca' => 1,
            'siniestro' => 1,
            'tierra' => 2,
            'veneno' => 1,
            'volador' => 2
        ],
        'lucha' => [
            'acero' => 2,
            'agua' => 1,
            'bicho' => 0.5,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 0,
            'fuego' => 1,
            'hada' => 0.5,
            'hielo' => 2,
            'lucha' => 1,
            'normal' => 2,
            'planta' => 1,
            'psiquico' => 0.5,
            'roca' => 2,
            'siniestro' => 2,
            'tierra' => 1,
            'veneno' => 0.5,
            'volador' => 0.5
        ],
        'normal' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 0,
            'fuego' => 1,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 1,
            'roca' => 0.5,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'planta' => [
            'acero' => 0.5,
            'agua' => 2,
            'bicho' => 0.5,
            'dragon' => 0.5,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 0.5,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 0.5,
            'psiquico' => 1,
            'roca' => 2,
            'siniestro' => 1,
            'tierra' => 2,
            'veneno' => 0.5,
            'volador' => 0.5
        ],
        'psiquico' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 2,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 1,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 2,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 0.5,
            'roca' => 1,
            'siniestro' => 0,
            'tierra' => 1,
            'veneno' => 2,
            'volador' => 1
        ],
        'roca' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 2,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 1,
            'fuego' => 2,
            'hada' => 1,
            'hielo' => 2,
            'lucha' => 0.5,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 1,
            'roca' => 1,
            'siniestro' => 1,
            'tierra' => 0.5,
            'veneno' => 1,
            'volador' => 2
        ],
        'siniestro' => [
            'acero' => 1,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 2,
            'fuego' => 1,
            'hada' => 0.5,
            'hielo' => 1,
            'lucha' => 0.5,
            'normal' => 1,
            'planta' => 1,
            'psiquico' => 2,
            'roca' => 1,
            'siniestro' => 0.5,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ],
        'tierra' => [
            'acero' => 2,
            'agua' => 1,
            'bicho' => 0.5,
            'dragon' => 1,
            'electrico' => 2,
            'fantasma' => 1,
            'fuego' => 2,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 0.5,
            'psiquico' => 1,
            'roca' => 2,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 2,
            'volador' => 0
        ],
        'veneno' => [
            'acero' => 0,
            'agua' => 1,
            'bicho' => 1,
            'dragon' => 1,
            'electrico' => 1,
            'fantasma' => 0.5,
            'fuego' => 1,
            'hada' => 2,
            'hielo' => 1,
            'lucha' => 1,
            'normal' => 1,
            'planta' => 2,
            'psiquico' => 1,
            'roca' => 0.5,
            'siniestro' => 1,
            'tierra' => 0.5,
            'veneno' => 0.5,
            'volador' => 1
        ],
        'volador' => [
            'acero' => 0.5,
            'agua' => 1,
            'bicho' => 2,
            'dragon' => 1,
            'electrico' => 0.5,
            'fantasma' => 1,
            'fuego' => 1,
            'hada' => 1,
            'hielo' => 1,
            'lucha' => 2,
            'normal' => 1,
            'planta' => 2,
            'psiquico' => 1,
            'roca' => 0.5,
            'siniestro' => 1,
            'tierra' => 1,
            'veneno' => 1,
            'volador' => 1
        ]
    ];
    public function calculateDamage(string $attackerPokemon, string $moveID, string $defenderPokemon)
    {

        $pokemonDef = \App\Models\Pokemon::orWhere('key', $defenderPokemon)->orWhere('name', $defenderPokemon)->orwhere('national_id', 'like', '%'.$defenderPokemon.'%')->first();
        $pokemonAtt = \App\Models\Pokemon::orWhere('national_id', 'like', '%'.$attackerPokemon.'%')->orWhere('key', $attackerPokemon)->orWhere('name', $attackerPokemon)->first();
        
        if (is_null($pokemonAtt)) {
            return "Doesn't exist Attacker pokemon please check your request and try again";
        }
        if (is_null($pokemonDef)) {
            return "Doesn't exist Defender Pokemon please check your request and try again";
        }

        $move = \App\Models\Move::where('id', '=', $moveID)->orWhere('key', '=', $moveID)->orWhere('name', '=', $moveID)->first();
        if (is_null($move)) {
            return "Doesn't exist this move, plrse check request and try again";
        }

        $effectivenessValue = $this->effectiveness[$move->type->key][$pokemonDef->types->first()->key];
        $levelPokemonAtt = $pokemonAtt->level;
        $baseAttackPokemonAtt = $pokemonAtt->base_attack;
        $movePower = $move->power;
        $baseDefPokemonDef = $pokemonDef->base_defense;
        $damage = (((2*$levelPokemonAtt/5+2)*$baseAttackPokemonAtt*$movePower/$baseDefPokemonDef)/50) * $effectivenessValue * rand(85, 100)/100;
        return $damage;
    }
}
